# Generated by Django 2.1.7 on 2019-03-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='years',
            new_name='age',
        ),
    ]
